name = "finki-diplomas-api"
main = "src/index.ts"
compatibility_date = "2025-02-06"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "diplomski-api.finki-hub.com/*"
zone_name = "finki-hub.com"
